#!/usr/bin/env ansible-playbook
---
- name: Setup a New Ubuntu Server
  hosts: kubecluster
  sudo: false
  vars:
     apt_mirror_ip_address: 192.168.1.132
  tasks: 
    - name: install apt sources.list with local mirror refernce
      sudo: true
      template: src=templates/apt-sources-list.j2 dest=/etc/apt/sources.list backup=yes mode=0644

    - name: Install Emacs
      sudo: true
      apt: name=emacs24-nox update_cache=true

    # Configure root's .bashrc
    # this could all be done as a single complex string in one lineinfile, but why?
    - name: Set Emacs editor preferences (root)
      sudo: true
      lineinfile: dest=~/.bashrc insertafter=EOF line="\n# Set emacs as prefered editor for shell env"

    - name: Set bash built in preference (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="set -o emacs"

    - name: Set EDITOR env var (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="export EDITOR=emacs"

    - name: Set VISUAL env var (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="export VISUAL=$EDITOR"

    # Configure ubnut user's .bashrc 
    - name: Set Emacs editor preferences (ubuntu)
      lineinfile: dest=~/.bashrc line="\n# Set emacs as prefered editor for shell env"

    - name: Set bash built in preference (ubuntu)
      lineinfile: dest=~/.bashrc line="set -o emacs"

    - name: Set EDITOR env var (ubuntu)
      lineinfile: dest=~/.bashrc line="export EDITOR=emacs"

    - name: Set VISUAL env var (ubuntu)
      lineinfile: dest=~/.bashrc line="export VISUAL=$EDITOR"

 
