#!/usr/bin/env ansible-playbook
---
- name: Setup a New Ubuntu Server
  hosts: kubecluster
  sudo: false
  vars:
     apt_mirror_ip_address: 192.168.1.132
  tasks: 
    - name: install apt sources.list with local mirror refernce
      sudo: true
      template: src=templates/apt-sources-list.j2 dest=/etc/apt/sources.list backup=yes mode=0644

    # An immediate refresh is required that we know will generate errors
    # for several indexes that aren't specified in the new sources.list
    # This calls for installing emacs, but we know it won't as soon as it
    # errors out.  We ignore the errors, and then immediately retry the
    # emacs installation - which should succede.
    - name: Refresh apt-cache w/ expected errors
      sudo: true
      apt: name=emacs24-nox update_cache=yes 
      ignore_errors: true

    - name: Install Emacs
      sudo: true
      apt: name=emacs24-nox update_cache=yes cache_valid_time=3600 state=installed

    # Configure root's .bashrc
    # this could all be done as a single complex string in one lineinfile, but why?
    - name: Set Emacs editor preferences (root)
      sudo: true
      lineinfile: dest=~/.bashrc insertafter=EOF line="\n# Set emacs as prefered editor for shell env"

    - name: Set bash built in preference (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="set -o emacs"

    - name: Set EDITOR env var (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="export EDITOR=emacs"

    - name: Set VISUAL env var (root)
      sudo: true
      lineinfile: dest=~/.bashrc line="export VISUAL=$EDITOR"

    # Configure ubnut user's .bashrc 
    - name: Set Emacs editor preferences (ubuntu)
      lineinfile: dest=~/.bashrc line="\n# Set emacs as prefered editor for shell env"

    - name: Set bash built in preference (ubuntu)
      lineinfile: dest=~/.bashrc line="set -o emacs"

    - name: Set EDITOR env var (ubuntu)
      lineinfile: dest=~/.bashrc line="export EDITOR=emacs"

    - name: Set VISUAL env var (ubuntu)
      lineinfile: dest=~/.bashrc line="export VISUAL=$EDITOR"

 
