---
- hosts: all
  become: yes
  tasks:

  # see http://docs.ansible.com/ansible/authorized_key_module.html
  - name: add the public rsa key to the ftl user's authorized_keys file
    authorized_key:
      user: ftl
      state: present
      key: "{{ lookup('file', './install_id_rsa.pub') }}"
