#!/usr/bin/env ansible-playbook
# Note: must be run with --ask-pass since keys are being established.
---	
- name: Setup ssh on Ubuntu Server 
  hosts: kubecluster
  sudo: false
  tasks: 
    - name: create .ssh dir
      file: dest=~/.ssh state=directory mode=0700

    - name: copy authorized_keys
      copy: src=files/authorized_keys dest=~/.ssh/authorized_keys
 